spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hooking?serverTimezone=Asia/Seoul
    username: root
    password: yexxi2118#

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  jwt:
    secret-key: yexxi2118#
    blacklist:
      access-token: BlackList_AccessToken_

  redis:
    host: ${HOST}
    port: 6379


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
