spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            redirect-uri: ${KAKAO_REDIRECT_URL}
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  jwt:
    secret-key: ${SECRET-KEY}
    blacklist:
      access-token: BlackList_AccessToken_

  redis:
    host: ${HOST}
    port: 6379


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

